checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '2'
        config_file: .pylintrc
filter:
    excluded_paths:
        - '*/tests/*'
build:
    environment:
        python: '3.5.0'
        redis: true
    dependencies:
        override:
            - 'pip install -r requirements.txt'
    tests:
        override:
            - pylint-run monitor.py
